version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest testthings.py
    environment:
      PYTHONPATH: /root/project/


workflows:
  version: 2
  build:
    jobs:
      - build